version: '3.1'
services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pa55word
      MYSQL_DATABASE: ecs_database
      MYSQL_USER: ecs_user
      MYSQL_PASSWORD: ecs_user